name: Release to brew
on:
  release:
    types: [created]

jobs:
  homebrew-pr:
    name: Homebrew Bump Formula PR
    runs-on: macos-10.15
    steps:
      - name: Get release tag name
        run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
      - name: Configure git user name and email
        uses: Homebrew/actions/git-user-config@master
        with:
          username: aws-viewer-for-cbmc-release-ci
      - name: Create homebrew PR
        run: |
          brew update-reset
          brew tap aws/tap
          brew bump-formula-pr --tag "$RELEASE_TAG" --revision "$GITHUB_SHA" aws/tap/cbmc-viewer
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.RELEASE_CI_ACCESS_TOKEN }}

  build-bottle:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, macos-10.15]
      runs-on: ${{ matrix.os }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - name: Set up Homebrew
          id: set-up-homebrew
          uses: Homebrew/actions/setup-homebrew@master

        - name: Cache Homebrew Bundler RubyGems
          id: cache
          uses: actions/cache@v1
          with:
            path: ${{ steps.set-up-homebrew.outputs.gems-path }}
            key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
            restore-keys: ${{ runner.os }}-rubygems-

        - name: Install Homebrew Bundler RubyGems
          if: steps.cache.outputs.cache-hit != 'true'
          run: brew install-bundler-gems
        - name: Get release tag name
          run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
        - name: Build bottle
          run: |
            brew tap aws/tap
            brew update-reset
            cd $(brew --repository)/Library/Taps/aws/homebrew-tap/
            git remote add fork-repo https://${{ secrets.RELEASE_CI_ACCESS_TOKEN }}@github.com/aws-build-accumulator-release-ci/homebrew-tap.git
            git fetch fork-repo
            git checkout -B bump-$RELEASE_TAG fork-repo/bump-$RELEASE_TAG
            cd -
            brew install --build-bottle aws/tap/cbmc-viewer
            brew bottle --root-url=https://github.com/ronakfof/viewer/releases/download/$RELEASE_TAG --verbose --json aws/tap/cbmc-viewer
        - name: Upload bottles as artifact
          if: always()
          uses: actions/upload-artifact@main
          with:
            name: bottles
            path: '*.bottle.*'
        - name: packages
          id: packages
          run: |
            bottle_name="$(ls *.tar.gz)"
            echo "::set-output name=bottle::$bottle_name"
            echo "::set-output name=bottle_name::$bottle_name"
        - name: Get release
          id: get_release_info
          uses: bruceadams/get-release@v1.2.3
        - name: Upload release binary
          uses: actions/upload-release-asset@v1.0.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.get_release_info.outputs.upload_url }}
            asset_path: ${{ steps.packages.outputs.bottle }}
            asset_name: ${{ steps.packages.outputs.bottle_name }}
            asset_content_type: application/x-gzip

    update-pr:
      needs: build-bottle
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_CI_ACCESS_TOKEN }}
      steps:
      - uses: actions/download-artifact@v3
        with:
          name: bottles
      - name: Configure git user name and email
        uses: Homebrew/actions/git-user-config@master
        with:
          username: aws-build-accumulator-release-ci
      - name: Get release tag name
        run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
      - name: fork and pr
        run: |
          brew tap aws/tap
          cd $(brew --repository)/Library/Taps/aws/homebrew-tap/
          git remote add fork-repo https://${{ secrets.RELEASE_CI_ACCESS_TOKEN }}@github.com/aws-build-accumulator-release-ci/homebrew-tap.git
          git fetch fork-repo
          git checkout -B bump-$RELEASE_TAG fork-repo/bump-$RELEASE_TAG
          cd -
          brew bottle --merge --write $(ls *.json)
          cd $(brew --repository)/Library/Taps/aws/homebrew-tap/
          git push fork-repo bump-$RELEASE_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_CI_ACCESS_TOKEN }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.RELEASE_CI_ACCESS_TOKEN }}
