name: Release to brew
on:
  release:
    types: [created]

env:
  RELEASE_TAG: ${GITHUB_REF/refs\/tags\/}
  VERSION: $(echo ${{ github.ref }} | cut -d "/" -f 3 | cut -d "-" -f 2)
  FORMULA: cbmc-viewer
  TAP: ronakfof/tap
  BOT_USER: aws-viewer-for-cbmc-release-ci
  FORK_REPO: https://${{ secrets.RELEASE_CI_ACCESS_TOKEN }}@github.com/${{ env.BOT_USER }}/homebrew-$(echo "${{ env.TAP }}"" | cut -d "/" -f 2).git
  ROOT_URL: https://github.com/$GITHUB_REPOSITORY/releases/download/${{ env.RELEASE_TAG }}

jobs:
  homebrew-pr:
    name: Homebrew Bump Formula PR
    runs-on: macos-10.15
    steps:
      - name: Configure git user name and email
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ env.BOT_USER }}

      - name: Create homebrew PR
        run: |
          brew update-reset
          brew tap ${{ env.TAP }}
          brew bump-formula-pr --tag "${{ env.RELEASE_TAG }}" --revision "$GITHUB_SHA" ${{ env.TAP }}/${{ env.FORMULA }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.RELEASE_CI_ACCESS_TOKEN }}

  build-bottle:
    needs: homebrew-pr
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-10.15]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Homebrew Bundler RubyGems
        run: brew install-bundler-gems

      - name: Checkout PR
        run: |
          brew tap ${{ env.TAP }}
          brew update-reset
          cd $(brew --repo ${{ env.TAP }})
          git remote add fork-repo ${{ env.FORK_REPO }}
          git fetch fork-repo
          git checkout -B bump-${{ env.FORMULA }}-${{ env.VERSION }} fork-repo/bump-${{ env.FORMULA }}-${{ env.VERSION }}

      - name: Build bottle
        run: |
          brew install --build-bottle ${{ env.TAP }}/${{ env.FORMULA }}
          brew bottle --root-url=${{ env.ROOT_URL }} --verbose --json ${{ env.TAP }}/${{ env.FORMULA }}

      - name: Upload bottles as artifact
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'

      - name: Get Package Path
        id: get_package_path
        run: |
          bottle_name="$(ls *.tar.gz)"
          echo "::set-output name=bottle::$bottle_name"

      - name: Get File Name
        id: get_file_name
        run: |
          brew install jq
          file_name="$(cat *.json | jq -r '."aws/tap/cbmc-viewer".bottle.tags[].filename')"
          echo "::set-output name=file_name::$file_name"

      - name: Get release
        id: get_release_info
        uses: bruceadams/get-release@v1.2.3

      - name: Upload release binary
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ${{ steps.get_package_path.outputs.bottle }}
          asset_name: ${{ steps.get_file_name.outputs.file_name }}
          asset_content_type: application/x-gzip

  update-pr:
    needs: build-bottle
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_CI_ACCESS_TOKEN }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: bottles

    - name: Configure git user name and email
      uses: Homebrew/actions/git-user-config@master
      with:
        username: ${{ env.BOT_USER }}

    - name: Checkout PR
      run: |
        brew tap ${{ env.TAP }}
        brew update-reset
        cd $(brew --repo ${{ env.TAP }})
        git remote add fork-repo ${{ env.FORK_REPO }}
        git fetch fork-repo
        git checkout -B bump-${{ env.FORMULA }}-${{ env.VERSION }} fork-repo/bump-${{ env.FORMULA }}-${{ env.VERSION }}

    - name: Generate and merge bottle DSL
      run: |
        brew bottle --merge --write $(ls *.json)
        cd $(brew --repository)/Library/Taps/aws/homebrew-tap/
        git -C $(brew --repo ${{ env.TAP }}) push fork-repo bump-cbmc-${{ env.RELEASE_TAG }}